// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUkCb7HRRu5_fJdgm_4Y9lYjttPcwb01g',
    appId: '1:1035941622883:web:dccb6b167457265d90f456',
    messagingSenderId: '1035941622883',
    projectId: 'memoryboxflutter',
    authDomain: 'memoryboxflutter.firebaseapp.com',
    storageBucket: 'memoryboxflutter.firebasestorage.app',
    measurementId: 'G-ZBNJBZWLS2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADDQC87HcxyCVTqRSLeFHdDgtgc2MFgZU',
    appId: '1:1035941622883:android:ced51d160f01a91f90f456',
    messagingSenderId: '1035941622883',
    projectId: 'memoryboxflutter',
    storageBucket: 'memoryboxflutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhUtAACMBBLlOWMOsmVRMMYHPpEXR94F0',
    appId: '1:1035941622883:ios:47d1da23d5de157290f456',
    messagingSenderId: '1035941622883',
    projectId: 'memoryboxflutter',
    storageBucket: 'memoryboxflutter.firebasestorage.app',
    iosBundleId: 'com.apostolov.memoryBoxAvada',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhUtAACMBBLlOWMOsmVRMMYHPpEXR94F0',
    appId: '1:1035941622883:ios:47d1da23d5de157290f456',
    messagingSenderId: '1035941622883',
    projectId: 'memoryboxflutter',
    storageBucket: 'memoryboxflutter.firebasestorage.app',
    iosBundleId: 'com.apostolov.memoryBoxAvada',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUkCb7HRRu5_fJdgm_4Y9lYjttPcwb01g',
    appId: '1:1035941622883:web:0c72cdac6508241d90f456',
    messagingSenderId: '1035941622883',
    projectId: 'memoryboxflutter',
    authDomain: 'memoryboxflutter.firebaseapp.com',
    storageBucket: 'memoryboxflutter.firebasestorage.app',
    measurementId: 'G-C5B7XKLJGK',
  );
}